# Yarn Modern configuration
# This file replaces .npmrc and .yarnrc from Yarn Classic

# Node linker: use node_modules (classic behavior)
# Remove this if you want to migrate to Plug'n'Play later
nodeLinker: node-modules

# Require packages to be published for at least 1440 minutes (24 hours) before installation
# This helps avoid installing packages that may be unpublished or have issues
npmMinimalAgeGate: 1440

