packages:
  - packages/*

catalog:
  "@graphql-codegen/cli": ^2.16.0
  "@graphql-codegen/plugin-helpers": ^2.7.0
  "@graphql-codegen/visitor-plugin-common": ^2.13.0
  "@graphql-tools/apollo-engine-loader": ^8.0.27
  "@graphql-tools/graphql-file-loader": ^7.5.13
  "@graphql-tools/load": ^7.8.8
  "@types/node": ^24
  auto-bind: ^4.0.0
  graphql: ^15.4.0
  lodash: 4.17.23
  npm-run-all: ^4.1.5
  rimraf: ^3.0.2
  ts-node: ^10.9.1
  tsdown: ^0.17.2
  typescript: ^5.9

onlyBuiltDependencies:
  - es5-ext
  - esbuild
  - husky
  - jss
  - spawn-sync

# 1 day in minutes
minimumReleaseAge: 1440

overrides:
  graphql: "catalog:"
