packages:
  - packages/*

catalog:
  "@graphql-codegen/cli": ^2.16.0
  "@graphql-codegen/plugin-helpers": ^2.7.0
  "@graphql-codegen/visitor-plugin-common": ^2.13.0
  "@graphql-tools/apollo-engine-loader": ^8.0.27
  "@graphql-tools/graphql-file-loader": ^7.5.13
  "@graphql-tools/load": ^7.8.8
  "@rollup/plugin-typescript": ^12.1.4
  "@types/node": ^24
  auto-bind: ^4.0.0
  graphql: ^15.4.0
  npm-run-all: ^4.1.5
  rimraf: ^3.0.2
  rollup: ^2.38.3
  rollup-plugin-gzip: ^4.1.1
  rollup-plugin-terser: ^7.0.2
  ts-node: ^10.9.1
  typescript: ^5.9
  tsdown: ^0.17.2
  lodash: 4.17.21

overrides:
  graphql: "catalog:"

onlyBuiltDependencies:
  - es5-ext
  - husky
  - jss
  - spawn-sync

# 1 day in minutes
minimumReleaseAge: 1440
