export const Sdk = {
  CONNECTION_CLASS: "Connection",
  CONNECTION_TYPE: "LinearConnection",
  CONNECTION_NAME: "connection",
  DATA_NAME: "data",
  DATA_TYPE: "Data",
  NAMESPACE: "L",
  NODE_NAME: "nodes",
  NODE_TYPE: "Node",
  FETCH_NAME: "fetch",
  FETCH_TYPE: "LinearFetch",
  PAGEINFO_NAME: "pageInfo",
  PAGEINFO_TYPE: "PageInfo",
  REQUEST_CLASS: "Request",
  REQUEST_NAME: "request",
  REQUEST_TYPE: "LinearRequest",
  RESPONSE_NAME: "response",
  RESPONSE_TYPE: "LinearResponse",
  SDK_CLASS: "LinearSdk",
  VARIABLE_NAME: "variables",
  VARIABLE_TYPE: "Variables",
};
