export const Doc = {
  CONNECTION_FIELDS: ["pageInfo", "nodes", "edges"],
  MUTATION_TYPES: [
    "update",
    "archive",
    "unarchive",
    "delete",
    "suspend",
    "unsuspend",
    "upgrade",
    "revoke",
    "rotateSecret",
    "create",
  ],
  SCALAR_STRING_NAMES: ["TimelessDateScalar"],
  SCALAR_STRING_TYPE: "string",
  SCALAR_DATE_NAMES: ["DateTime", "TimelessDateScalar"],
  SCALAR_DATE_TYPE: "Date",
  SCALAR_JSON_NAMES: ["JSON"],
  SCALAR_JSON_TYPE: "Record<string, unknown>",
  SCALAR_DATE_OR_STRING_NAMES: ["DateTimeOrDuration"],
  SCALAR_DATE_OR_STRING_TYPE: "Date | string",
  SCALAR_NOTIFICATION_TYPE_MAP: {
    IssueAssignedToYouNotificationType: "issueAssignedToYou",
    IssueMentionNotificationType: "issueMention",
    IssueUnassignedFromYouNotificationType: "issueUnassignedFromYou",
    IssueEmojiReactionNotificationType: "issueEmojiReaction",
    IssueCommentMentionNotificationType: "issueCommentMention",
    IssueCommentReactionNotificationType: "issueCommentReaction",
    IssueNewCommentNotificationType: "issueNewComment",
    IssueStatusChangedNotificationType: "issueStatusChanged",
  },
};
