export default {
  CONNECTION_CLASS: "LinearConnection",
  CONNECTION_TYPE: "Connection",
  DATA_NAME: "data",
  DATA_TYPE: "Data",
  NAMESPACE: "D",
  NODE_NAME: "nodes",
  NODE_TYPE: "Node",
  FETCH_NAME: "fetch",
  FETCH_TYPE: "Fetch",
  PAGEINFO_NAME: "pageInfo",
  PAGEINFO_TYPE: "PageInfo",
  REQUEST_CLASS: "LinearRequest",
  REQUEST_NAME: "request",
  REQUEST_TYPE: "Request",
  RESPONSE_NAME: "response",
  RESPONSE_TYPE: "Response",
  SDK_CLASS: "LinearSdk",
  VARIABLE_NAME: "variables",
  VARIABLE_TYPE: "Variables",
};
