export default {
  HANDLER_NAME: "handler",
  HANDLER_TYPE: "LinearHandler",
  ID_NAME: "id",
  ID_TYPE: "string",
  NAMESPACE_DOCUMENT: "D",
  NAMESPACE_TYPE: "T",
  OPTIONS_NAME: "opts",
  OPTIONS_TYPE: "O",
  REQUESTER_NAME: "requester",
  REQUESTER_TYPE: "LinearRequester",
  RESPONSE_NAME: "response",
  RESPONSE_TYPE: "LinearResponse",
  SDK_NAME: "createRawLinearSdk",
  SDK_TYPE: "LinearSdk",
  STATUS_TYPE: "LinearStatus",
  VARIABLE_NAME: "vars",
};
