export default {
  HANDLER_NAME: "linearHandler",
  HANDLER_TYPE: "LinearHandler",
  ID_NAME: "id",
  ID_TYPE: "string",
  NAMESPACE_DOCUMENT: "D",
  NAMESPACE_TYPE: "T",
  OPTIONS_NAME: "opts",
  REQUESTER_NAME: "requester",
  REQUESTER_TYPE: "Requester",
  RESPONSE_TYPE: "LinearResponse",
  SDK_NAME: "createRawLinearSdk",
  SDK_TYPE: "LinearSdk",
  STATUS_TYPE: "LinearStatus",
  VARIABLE_NAME: "vars",
  WRAPPER_DEFAULT_NAME: "defaultWrapper",
  WRAPPER_NAME: "wrapper",
  WRAPPER_TYPE: "LinearWrapper",
};
