name: dependencies

on:
  workflow_dispatch:

permissions: {}

jobs:
  dependencies:
    name: Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0

      - name: Use node 22
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Update dependencies
        run: pnpm update:dependencies

      - name: Build packages
        run: pnpm build

      - name: Run tests
        run: pnpm test

      - name: Create dependencies pull request
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7.0.11
        with:
          sign-commits: true
          commit-message: "chore(release): update dependencies"
          title: "chore(release): update dependencies"
          body: "Update dependencies"
          branch: dependencies
          base: master

  notify-slack:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [dependencies]
    permissions:
      actions: read
      contents: read
    if: ${{ always() && github.ref_name == 'master' && contains(needs.*.result, 'failure') }}
    steps:
      - uses: ravsamhq/notify-slack-action@bca2d7f5660b833a27bda4f6b8bef389ebfefd25 # 2.3.0
        with:
          status: ${{ job.status }}
          token: ${{ secrets.GITHUB_TOKEN }}
          notification_title: "SDK CI check failed on master branch"
          message_format: ":x: Check failed in <{repo_url}|{repo}@{branch}> on <{commit_url}|{commit_sha}>"
          footer: <{run_url}|View Run>
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
