name: Static Analysis GH Actions (zizmor)

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["**"]
  merge_group:

permissions: {}

jobs:
  zizmor:
    name: Run zizmor
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        timeout-minutes: 2
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@e673c3917a1aef3c65c972347ed84ccd013ecda4 # v0.2.0
        with:
          inputs: .github/
          min-severity: medium
          advanced-security: false
          version: v1.24.1
